### ISSUE TITLE
How to get images?

### ISSUE THREAD

**Issue by mvidner** [yast/yast-docker#1]
It works! I have run the module. (As root, otherwise it reports an internal error with EACCESS on `/var/run/docker.sock`)

So I have an empty table and obviously I need to add images. It would be nice it the module assisted me with that, or at least gave me an URL of a how-to.

**Comment by eduardoj** [comment]
> If you want to download other images you have to use the `docker pull <image>` command. It would have been nice to integrate that into the whole YaST ui, but we didn't have time for that.

With #14 a `docker pull <image>` can be done into the YaST ui.

**Comment by dgdavid** [comment]
I has been testing the work of @eduardoj and, as far as I can see, it almost work (prompts a communication with docker error when pulling an image, for example). However, the PR is closed and seems that nobody has been interested in such feature for a long time. And I fear the situation is going to be quit the same in a long term.

Then, I'll close the issue too.

Feel free to reopen it if you are interested on taking care about such feature.
