### ISSUE TITLE
docker-compose support

### ISSUE THREAD

**Issue by rtrauntvein** [yast/yast-docker#9]
What are your thoughts on docker-compose support for this yast module? It would be cool to be able to install SUSE, open the yast-docker module, and then launch a docker-compose service

I guess this would require a packaged version of docker-compose and there would also need to be some way to paste in or specify a path to a `docker-compose.yml`

**Comment by danelder** [comment]
More integration with YaST will make it easier for beginners to get started while still exposing all the bits underneath for those who are more advanced.

**Comment by flavio** [comment]
We already offer a packaged version of compose. For openSUSE this is on OBS
Virtualization:containers. For SLE customers it is part of the containers
module.

As for the compose integration with yast2-docker this is not planned right
now. This module is just a quick way to get started with docker.

IMO having to fire up a UI to use compose would just show down the whole
workflow.
